USE [master]
GO

/****** Object:  Database [projekt-obiektDB]    Script Date: 01.01.2023 17:28:35 ******/
CREATE DATABASE [projekt-obiektDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'projekt-obiektDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\projekt-obiektDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'projekt-obiektDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\projekt-obiektDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [projekt-obiektDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [projekt-obiektDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [projekt-obiektDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [projekt-obiektDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [projekt-obiektDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [projekt-obiektDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [projekt-obiektDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [projekt-obiektDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [projekt-obiektDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [projekt-obiektDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [projekt-obiektDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [projekt-obiektDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [projekt-obiektDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [projekt-obiektDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [projekt-obiektDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [projekt-obiektDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [projekt-obiektDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [projekt-obiektDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [projekt-obiektDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [projekt-obiektDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [projekt-obiektDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [projekt-obiektDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [projekt-obiektDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [projekt-obiektDB] SET RECOVERY FULL 
GO

ALTER DATABASE [projekt-obiektDB] SET  MULTI_USER 
GO

ALTER DATABASE [projekt-obiektDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [projekt-obiektDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [projekt-obiektDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [projekt-obiektDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [projekt-obiektDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [projekt-obiektDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [projekt-obiektDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [projekt-obiektDB] SET  READ_WRITE 
GO

